/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class TerminkalenderDialog extends javax.swing.JDialog
{

    /**
     * Creates new form TerminkalenderDialog
     */
    public TerminkalenderDialog(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lbDay = new javax.swing.JLabel();
        tfDay = new javax.swing.JTextField();
        lbMonth = new javax.swing.JLabel();
        tfMonth = new javax.swing.JTextField();
        lbYear = new javax.swing.JLabel();
        tfYear = new javax.swing.JTextField();
        lbHour = new javax.swing.JLabel();
        tfHour = new javax.swing.JTextField();
        lbMin = new javax.swing.JLabel();
        tfMin = new javax.swing.JTextField();
        lbText = new javax.swing.JLabel();
        tfText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(7, 2));

        lbDay.setText("Tag: ");
        getContentPane().add(lbDay);

        tfDay.setText("jTextField1");
        getContentPane().add(tfDay);

        lbMonth.setText("Monat: ");
        getContentPane().add(lbMonth);

        tfMonth.setText("jTextField1");
        getContentPane().add(tfMonth);

        lbYear.setText("Jahr: ");
        getContentPane().add(lbYear);

        tfYear.setText("jTextField1");
        getContentPane().add(tfYear);

        lbHour.setText("Stunde: ");
        getContentPane().add(lbHour);

        tfHour.setText("jTextField1");
        getContentPane().add(tfHour);

        lbMin.setText("Minute: ");
        getContentPane().add(lbMin);

        tfMin.setText("jTextField1");
        getContentPane().add(tfMin);

        lbText.setText("Text: ");
        getContentPane().add(lbText);

        tfText.setText("jTextField1");
        getContentPane().add(tfText);

        jButton1.setText("übernehmen");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);

        jButton2.setText("abbrechen");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(TerminkalenderDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(TerminkalenderDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(TerminkalenderDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(TerminkalenderDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                TerminkalenderDialog dialog = new TerminkalenderDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel lbDay;
    private javax.swing.JLabel lbHour;
    private javax.swing.JLabel lbMin;
    private javax.swing.JLabel lbMonth;
    private javax.swing.JLabel lbText;
    private javax.swing.JLabel lbYear;
    private javax.swing.JTextField tfDay;
    private javax.swing.JTextField tfHour;
    private javax.swing.JTextField tfMin;
    private javax.swing.JTextField tfMonth;
    private javax.swing.JTextField tfText;
    private javax.swing.JTextField tfYear;
    // End of variables declaration//GEN-END:variables
}
